QUESTION 1

In [1]:
import numpy as np
np.arange(2,50,3)

array([ 2,  5,  8, 11, 14, 17, 20, 23, 26, 29, 32, 35, 38, 41, 44, 47])

QUESTION 2

In [1]:
import numpy as np
list1=[]
print("enter elements for 1st list\n")
n=5
for i in range(0,n):
    ele=int(input())
    list1.append(ele)
list2=[]
print("enter elements for 2nd list\n")
n=5
for i in range(0,n):
    ele=int(input())
    list2.append(ele)

ar1=np.array(list1)
ar2=np.array(list2)
print("list1:",list1)
print("list2:",list2)
print("array1:",ar1)
print("array2:",ar2)
ar3=np.array(np.concatenate((ar1,ar2)))
print("concatenated array:",ar3)
print("sorted array1:")
print(np.sort(ar1))
print("sorted array2:")
print(np.sort(ar2))
print("sorted concatenated array:")
print(np.sort(ar3))


enter elements for 1st list

0
9
8
7
6
enter elements for 2nd list

5
4
3
2
1
list1: [0, 9, 8, 7, 6]
list2: [5, 4, 3, 2, 1]
array1: [0 9 8 7 6]
array2: [5 4 3 2 1]
concatenated array: [0 9 8 7 6 5 4 3 2 1]
sorted array1:
[0 6 7 8 9]
sorted array2:
[1 2 3 4 5]
sorted concatenated array:
[0 1 2 3 4 5 6 7 8 9]


QUESTION 3

In [1]:
import numpy as np
arr=np.array([[2,3,4],[5,6,7],[1,8,9]])
print(arr)
print("dimension:",arr.ndim,"\n size:",arr.size)

[[2 3 4]
 [5 6 7]
 [1 8 9]]
dimension: 2 
 size: 9


QUESTION 4

In [2]:
import numpy as np
arr1=np.array([1,2,3,4])
print("1D array:",arr1)
rearr=np.reshape(arr1,(-1,2))
print("reshaped 2D:",rearr)

1D array: [1 2 3 4]
reshaped 2D: [[1 2]
 [3 4]]


In [1]:
import numpy as np
x=np.array([2,5,18,14,4])
y=x[:,np.newaxis]
print(y)

[[ 2]
 [ 5]
 [18]
 [14]
 [ 4]]


QUESTION 5

In [1]:
import numpy as np
arr1=np.array([[2,3],[3,6]])
arr2=np.array([[5,8],[6,9]])
print("vertical stacking:\n",np.vstack((arr1,arr2)))
print("horizontal stacking:\n",np.hstack((arr1,arr2)))

vertical stacking:
 [[2 3]
 [3 6]
 [5 8]
 [6 9]]
horizontal stacking:
 [[2 3 5 8]
 [3 6 6 9]]


QUESTION 6

In [5]:
list=[1,3,2,5,2,3,1,6]
a_set=set(list)
no_of_unique_values=len(a_set)
print(no_of_unique_values)

5
